# Generated by Django 5.0.6 on 2024-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('doc_year', models.IntegerField()),
                ('remarks', models.CharField(max_length=150)),
                ('filing_ref', models.CharField(max_length=60)),
                ('fund', models.CharField(max_length=10)),
            ],
        ),
    ]
