# Generated by Django 5.0.6 on 2024-10-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsInventoryHandler', '0003_document_date_received_document_time_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='MultiFiles/Inventory'),
        ),
    ]
