# Generated by Django 5.0.6 on 2024-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsInventoryHandler', '0005_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_month',
            field=models.IntegerField(default=10, max_length=12),
        ),
    ]
