# Generated by Django 5.0.6 on 2024-10-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsInventoryHandler', '0007_alter_document_doc_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_month',
            field=models.IntegerField(),
        ),
    ]
