# Generated by Django 5.0.6 on 2024-10-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsInventoryHandler', '0009_document_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='time_received',
            field=models.TimeField(),
        ),
    ]
