# Generated by Django 5.0.6 on 2024-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsInventoryHandler', '0010_alter_document_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='MultiFiles/Inventory/thumbnail'),
        ),
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='MultiFiles/Inventory/attachment'),
        ),
    ]
